// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AMapControlBar: typeof import('./../src/components/AMap/ControlBar/index.vue')['default']
    AMapFitView: typeof import('./../src/components/AMap/FitView/index.vue')['default']
    AMapGeolocation: typeof import('./../src/components/AMap/Geolocation/index.vue')['default']
    AMapMap: typeof import('./../src/components/AMap/Map/index.vue')['default']
    AMapMapType: typeof import('./../src/components/AMap/MapType/index.vue')['default']
    AMapMarker: typeof import('./../src/components/AMap/Marker/index.vue')['default']
    AMapScale: typeof import('./../src/components/AMap/Scale/index.vue')['default']
    AMapSearch: typeof import('./../src/components/AMap/Search/index.vue')['default']
    AMapToolbar: typeof import('./../src/components/AMap/Toolbar/index.vue')['default']
    AMapVector: typeof import('./../src/components/AMap/Vector/index.vue')['default']
    FenceView: typeof import('./../src/components/Fence/view/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
